package tech.murilo.stringsconcatbuilder;

public class LoremIpsumText {
	
	public static String LOREM_TEXT_01 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis et ex in semper. Curabitur auctor quam quis mi iaculis porttitor. Aenean maximus dignissim mauris, ut gravida tellus pretium ut. Proin facilisis et lacus at suscipit. Pellentesque sollicitudin arcu vel purus blandit feugiat. Cras at augue eu mauris consectetur lobortis. Vestibulum venenatis id odio sollicitudin tristique. Nulla viverra justo at nisl vestibulum, ut cursus turpis posuere. Pellentesque pulvinar orci turpis, non lobortis ipsum semper sit amet. Donec libero nunc, iaculis sed risus a, bibendum vestibulum nunc.\n";
	public static String LOREM_TEXT_02 = "Donec a rutrum velit, eu sodales libero. Nullam pharetra tortor non quam sagittis hendrerit. In placerat rhoncus nulla at ultrices. In imperdiet convallis posuere. Aliquam vel laoreet quam. Pellentesque et placerat tellus, eget placerat ex. Phasellus venenatis quam at maximus sagittis. Aliquam venenatis arcu nisi, vitae mattis eros pretium a. Aenean a pharetra nibh. Sed vestibulum massa mauris, vitae viverra ex congue sed. In id vulputate neque. Aliquam eu ornare massa, quis hendrerit quam. Phasellus ornare vehicula bibendum. Suspendisse porta ut ligula a egestas.\n";
	public static String LOREM_TEXT_03 = "Duis fringilla porttitor elit, ac consectetur est dictum quis. Suspendisse porttitor quam eu lorem tempus, vitae lacinia nisl molestie. Proin vitae dui eget nibh venenatis tempus. Morbi blandit magna elementum, commodo massa auctor, elementum elit. Sed fermentum dapibus augue et lobortis. Nunc imperdiet, arcu ac pretium fermentum, velit ex suscipit nunc, et porttitor felis dui sed ipsum. Mauris rutrum leo aliquam sollicitudin euismod. Morbi ante nunc, placerat sed sapien ut, viverra rutrum tortor. Nullam consequat nunc non velit efficitur, eu finibus nibh scelerisque. Maecenas scelerisque cursus facilisis. Donec dignissim placerat mauris, in faucibus lorem ultricies eu. Ut dolor velit, porttitor sit amet justo ut, ultrices condimentum eros. Nam posuere euismod lobortis. Nulla id ipsum consectetur, tincidunt nisl sed, convallis orci. Nullam luctus dignissim dignissim.\n";
	public static String LOREM_TEXT_04 = "Fusce a euismod ante, ullamcorper varius lectus. Suspendisse convallis molestie lacinia. Etiam quis velit vehicula, interdum lacus vel, ultricies lectus. Curabitur ac neque neque. In risus sem, pharetra id libero a, bibendum auctor lorem. Donec luctus arcu elit. Mauris eget nulla bibendum, vulputate lectus eu, pharetra turpis. Morbi sapien nisl, ullamcorper sit amet arcu ut, porta rutrum nunc. Nullam congue dui vitae nunc dapibus vulputate. Donec a dui vitae nisi aliquet cursus quis vel justo. Proin tellus risus, blandit vitae finibus at, sollicitudin ut enim. Phasellus suscipit vitae elit in tempus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras eget pharetra risus, ornare egestas ante. Etiam placerat eros orci, eget malesuada mauris semper sollicitudin.\n";
	public static String LOREM_TEXT_05 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut in nulla enim. In in luctus quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus a odio at enim pretium iaculis. Donec vestibulum risus at sem iaculis dictum. Aliquam erat volutpat. Fusce pellentesque ac nisl sollicitudin porta. Sed ut euismod ipsum.\n";

}
